"""Initial migration.

Revision ID: 644d2a9214c6
Revises: 
Create Date: 2023-09-03 18:06:07.231276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644d2a9214c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('risk_level', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_name'), ['name'], unique=False)

    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_portfolio')
    op.drop_table('resource')
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_name'))

    op.drop_table('investment')
    # ### end Alembic commands ###
